### ISSUE TITLE
Rendering issue with any non-vanilla barrel

### ISSUE THREAD

**Issue by encodebow** [MarioAndWeegee3/Iron-Barrels#2]
Hello,

As someone else has reported on the curse forge page, I am experiencing the rendering bug when opening any upgraded chest (e.g. iron or gold). They reported it in the comments of the mod here: https://www.curseforge.com/minecraft/mc-mods/iron-barrels?comment=10 (inventory sorting doesn't fix it for me).

When I first installed the mod it worked fine, however upon exiting & re-launching I can now no longer see the true inventory of upgraded barrels (non-vanilla).

The below screenshot shows how my item bar is replicated into the top of my inventory, and my actual inventory is replicated into the "new" rows in the iron barrel. 
![image](https://user-images.githubusercontent.com/53396347/62005127-d31cc200-b12e-11e9-9e0b-41cc44d1c654.png)

Also notice how it says "ironbarrels.wood" at the top, and this is the same when opening a gold barrel. I imagine this might be the cause of the issue?

I've tried launching without optifine/optifabric etc. and various other mods and it seems to not have any other affect.

It makes the upgraded barrels unusable as I've no idea what's in the extra slots.

**Note**: the items are NOT duplicated, if i try and move them around etc. I see exceptions in the logs about those items not existing, and they will revert back to where they were (e.g. if I try and take the golden apple from the chest it will disappear once I close the chest and try and click on it in inventory, but my legitimate apple is still there in my inventory.

**Comment by encodebow** [comment]
Further to the above, if I create a new Iron Barrel and place it like so:
![image](https://user-images.githubusercontent.com/53396347/62005372-8aff9e80-b132-11e9-87f0-3a54b3a48dba.png)

Then I save & quit into minecraft menu, and reload the world, upon opening the same barrel it now shows:
![image](https://user-images.githubusercontent.com/53396347/62005375-a4a0e600-b132-11e9-9223-c444858bcbdc.png)

It seems like it's not registering the barrels once the world is loaded as the proper entities (as implied by the name change at top of the barrel).

**Comment by encodebow** [comment]
I've looked into it more and if I break the barrels, I only get the items that were stored in first three rows, meaning any items that aren't in vanilla rows are 100% lost.

I see there's newer versions of this mod on the curse forge site than on GitHub, can you update the repo with the latest changes?

**Comment by MarioAndWeegee3** [comment]
Fixed
